In [33]:
import numpy as np
import numpy.random as rand
a = np.random.sample((10, 3))
print(a)
v = 0.5
b = (np.abs(a-v)).argmin(axis = 1)
i = 0
while i < 10:
    print(a[i][b[i]])
    i += 1


[[0.50379346 0.76833202 0.49815554]
 [0.55229625 0.87649655 0.37201348]
 [0.11528498 0.02554583 0.38242564]
 [0.25686775 0.8702109  0.24533288]
 [0.32874801 0.52869503 0.07929332]
 [0.31877238 0.76720981 0.52696123]
 [0.57282546 0.40308501 0.54216067]
 [0.22650126 0.34839817 0.74292113]
 [0.88374724 0.94649435 0.3212804 ]
 [0.01181837 0.56480996 0.25532449]]
0.4981555442107293
0.5522962549326058
0.3824256425746051
0.256867750966171
0.5286950345244594
0.5269612285585057
0.5421606747288173
0.3483981677617599
0.3212804047862996
0.5648099592929717


In [45]:
c = rand.random((6,6))
print(c)
i = 0
while i < 6:
    print("\n",np.sum(c[i])/c[c.argmin(axis = 0)[i]][i])
    i += 1

[[0.57811791 0.52729909 0.00987525 0.73758188 0.3430424  0.35326238]
 [0.70561402 0.00757121 0.68353194 0.59307438 0.33822637 0.48769605]
 [0.82727205 0.85852961 0.20509105 0.86763556 0.00118618 0.31240702]
 [0.04201254 0.50991046 0.25372784 0.69288261 0.33275083 0.33396147]
 [0.02135074 0.7318288  0.31637015 0.99613625 0.76821342 0.2941337 ]
 [0.46748616 0.89163185 0.30960671 0.28585473 0.90826753 0.76003246]]

 119.39535848155819

 371.8973202869471

 311.0931377785636

 7.57463682983491

 2637.0639962587184

 12.317117813489407


In [48]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x = x.tolist()
i = 0
max = 0
while i < 8:
    try:
        i = x.index(0, i, 8) + 1
    except:
        break
    if i == 8 :
        break
    if max < x[i]: 
        max = x[i]
print(max)

5


In [49]:
x = np.ones(10)
print(x)
index = np.array([0, 1, 2, 3, 5, 5, 5, 8])
j = 0
while j < 8:
    x[index[j]] += 1
    j += 1
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [55]:
N = input ("Введите N: ")
N = int(N)
a = np.arange(N * N).reshape(N, N)
d = {}
i = 0
while i < 2*N - 1:
    d[i] = []
    i += 1
i = 0
while i < N:
    j = 0
    while j < N:
        d.get(i + j).append(a[i][j])
        j += 1
    i += 1
print(d)

Введите N: 10
{0: [0], 1: [1, 10], 2: [2, 11, 20], 3: [3, 12, 21, 30], 4: [4, 13, 22, 31, 40], 5: [5, 14, 23, 32, 41, 50], 6: [6, 15, 24, 33, 42, 51, 60], 7: [7, 16, 25, 34, 43, 52, 61, 70], 8: [8, 17, 26, 35, 44, 53, 62, 71, 80], 9: [9, 18, 27, 36, 45, 54, 63, 72, 81, 90], 10: [19, 28, 37, 46, 55, 64, 73, 82, 91], 11: [29, 38, 47, 56, 65, 74, 83, 92], 12: [39, 48, 57, 66, 75, 84, 93], 13: [49, 58, 67, 76, 85, 94], 14: [59, 68, 77, 86, 95], 15: [69, 78, 87, 96], 16: [79, 88, 97], 17: [89, 98], 18: [99]}
